language: node_js
node_js:
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"
  - "iojs"

compiler: gcc
sudo: false

os:
  - linux
  - osx

addons:
  apt:
    packages:
      - gcc-4.7
      - g++-4.7

before_install:
  - npm install -g typescript
  - npm install -g tsd
  - npm install -g mocha
  - node --version
  - npm --version
  - gcc --version
  - g++ --version

script:
  - npm install
  - npm test

cache:
  directories:
    - $HOME/.node-gyp
    - $HOME/.npm
    - node_modules
