  os: Visual Studio 2013

  configuration: release

  platform:
    - x64
    - x86

  version: "{build}"

  clone_folder: c:\projects\trusted-crypto

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    matrix:
      - nodejs_version: 0.12
      - nodejs_version: 4
      - nodejs_version: 5
      - nodejs_version: 6

  before_install:
    - npm install -g typescript
    - npm install -g tsd
    - npm install -g mocha

  script:
    - npm install
    - npm test

  deploy:
    provider: GitHub
    auth_token:
        secure: f7734918d31d322cb25f2ea530b3dcbec60a9a91
    on:
        branch: master
        appveyor_repo_tag: true
