 -
  os: Visual Studio 2013

  configuration: release

  platform:
    - x64
    - x86


  version: "{build}"

  clone_folder: c:\projects\trusted-crypto

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    matrix:
      - nodejs_version: 4
      - nodejs_version: 5
      - nodejs_version: 6

  install:
    - if "%PLATFORM%"=="x86" SET OPENSSL_LIB_DIR=C:/OpenSSL-Win32
    - if "%PLATFORM%"=="x64" SET OPENSSL_LIB_DIR=C:/OpenSSL-Win64
    - node --version
    - npm --version
    - npm install -g typescript
    - npm install -g typings
    - npm install -g mocha
    - npm install --openssl_root=OPENSSL_LIB_DIR

  test_script:
    - npm test

  deploy:
    provider: GitHub
    auth_token:
        secure: f7734918d31d322cb25f2ea530b3dcbec60a9a91
    on:
        branch: master
        appveyor_repo_tag: true
